image: ubuntu:latest
variables:
  WORK_DIR: /home/admin/client/leaderbridge/leaderbridge-backend
  BRANCH: main
  REPO: https://gitlab.com/rejoicehub/leaderbridge/leaderbridge-backend.git
stages:
  - deploy
deploy:
  stage: deploy
  only:
    - main
  environment:
    name: development
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - rm -rf .git
    - ssh admin@"$REJOICEDEV" "cd ${WORK_DIR}; git pull; npm install; pm2 delete leaderbridge-backend; pm2 start app.yml"